services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - API_URL=${API_URL}
    image: shopco-frontend:latest
    container_name: shopco-frontend
    restart: unless-stopped
    networks:
      - traefik-net
    # Traefik configuration
    labels:
      - traefik.enable=true
      - traefik.http.routers.shopco.rule=Host(`shopco.${DOMAIN}`)
      - traefik.http.services.shopco.loadbalancer.server.port=80
      - traefik.http.routers.shopco.entrypoints=websecure
      - traefik.http.routers.shopco.tls=true
      - traefik.http.routers.shopco.tls.certresolver=cloudflare
      - traefik.http.routers.shopco.service=shopco

networks:
  traefik-net:
    external: true # Use the existing network that Traefik is connected to
